#!/bin/sh

echo "<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>1 seitig</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>1 seitig</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>com.apple.print.DocumentTicket.PMSpoolFormat</key>
			<string>application/pdf</string>
			<key>com.apple.print.JobInfo.PMJobName</key>
			<string>Whiskas German Brand list v2</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>819.21258544921875</real>
					<real>572.598388671875</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-11.33856201171875</real>
					<real>-11.338600158691406</real>
					<real>830.55120849609375</real>
					<real>583.93695068359375</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>1x2 seitig</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>1x2 seitig</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>com.apple.print.DocumentTicket.PMSpoolFormat</key>
			<string>application/pdf</string>
			<key>com.apple.print.JobInfo.PMJobName</key>
			<string>Whiskas German Brand list v2</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>819.21258544921875</real>
					<real>572.598388671875</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-11.33856201171875</real>
					<real>-11.338600158691406</real>
					<real>830.55120849609375</real>
					<real>583.93695068359375</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>2x2 seitig</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>2x2 seitig</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>StapleStatus</key>
			<string>274</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>3</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>819.21258544921875</real>
					<real>572.598388671875</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-11.33856201171875</real>
					<real>-11.338600158691406</real>
					<real>830.55120849609375</real>
					<real>583.93695068359375</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 1:1 Hoch</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 1:1 Hoch</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>Custom</key>
			<string>Off</string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string>Temp Tracken</string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>Off</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>1200dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>273</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PageFormat.PMAdjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PageFormat.PMAdjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 1:1 Normal</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 1:1 Normal</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>Custom</key>
			<string>Off</string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string></string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>On</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>600dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>273</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.APIVersion</key>
					<string>01.00</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 1:1 Normal Duplex</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 1:1 Normal Duplex</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BookletBinding</key>
			<false/>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>ColorModel</key>
			<string>Gray</string>
			<key>DuplexBindingEdge</key>
			<integer>2</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string></string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>On</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>600dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>273</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.APIVersion</key>
					<string>01.00</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 1:1 Super</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 1:1 Super</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>Custom</key>
			<string>Off</string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string></string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>Off</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>1200dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>273</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.APIVersion</key>
					<string>01.00</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 2:1 Entwurf Duplex</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 2:1 Entwurf Duplex</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string>Temp Tracken</string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>On</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>300dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>274</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>3</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PageFormat.PMAdjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PageFormat.PMAdjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 2:1 Normal</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 2:1 Normal</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>Custom</key>
			<string>Off</string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string>Temp Tracken</string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>On</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>600dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>274</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PageFormat.PMAdjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PageFormat.PMAdjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 2:1 Normal Duplex</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 2:1 Normal Duplex</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string></string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>On</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>600dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>274</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>3</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.APIVersion</key>
					<string>01.00</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>A4 SW 2:1 Normal Duplex 1</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>A4 SW 2:1 Normal Duplex 1</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>CaBrightness</key>
			<string>0</string>
			<key>CaColorMode</key>
			<string>0</string>
			<key>CaContrast</key>
			<string>0</string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string></string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KCEcoprint</key>
			<string>On</string>
			<key>KCUserLogin</key>
			<string>False</string>
			<key>KmCoverModeState</key>
			<string>Off</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobAccountingState</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>KmManagment</key>
			<string>Default</string>
			<key>KmPageinsertState</key>
			<string>Off</string>
			<key>KmTransparencyinterleavingState</key>
			<string>Off</string>
			<key>KmUserLoginEnabled</key>
			<string>Off</string>
			<key>KmUserLoginIDValue</key>
			<string></string>
			<key>KmUserLoginPasswordValue</key>
			<string></string>
			<key>KmUserLoginPromptAtPrint</key>
			<string>YES</string>
			<key>KmWatermarkState</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>Plain</string>
			<key>OutputBin</key>
			<string>None</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>600dpi</string>
			<key>Smoothing</key>
			<string>True</string>
			<key>StapleStatus</key>
			<string>274</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMColorSpaceModel</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>3</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>2147483647</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.preset.Orientation</key>
			<integer>1</integer>
			<key>com.apple.print.preset.PaperInfo</key>
			<dict>
				<key>paperInfo</key>
				<dict>
					<key>PMPPDPaperCodeName</key>
					<string>A4</string>
					<key>PMPPDTranslationStringPaperName</key>
					<string>A4</string>
					<key>PMTiogaPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMCustomPaper</key>
					<false/>
					<key>com.apple.print.PaperInfo.PMPaperName</key>
					<string>iso-a4</string>
					<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
					<array>
						<integer>0</integer>
						<integer>0</integer>
						<real>822</real>
						<real>571</real>
					</array>
					<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
					<array>
						<real>-10</real>
						<real>-12</real>
						<real>832</real>
						<real>583</real>
					</array>
					<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
					<string>A4</string>
					<key>com.apple.print.ticket.APIVersion</key>
					<string>01.00</string>
					<key>com.apple.print.ticket.type</key>
					<string>com.apple.print.PaperInfoTicket</string>
				</dict>
			</dict>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>822</real>
					<real>571</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-10</real>
					<real>-12</real>
					<real>832</real>
					<real>583</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>Standard Qualität 1:1 Duplex SW A4</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>Standard Qualität 1:1 Duplex SW A4</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BookletBinding</key>
			<false/>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>ColorModel</key>
			<string>Gray</string>
			<key>DuplexBindingEdge</key>
			<integer>2</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string>Dokument1</string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>PrnDef</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>600dpi</string>
			<key>StapleStatus</key>
			<string>273</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>806</real>
					<real>559</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-18</real>
					<real>-18</real>
					<real>824</real>
					<real>577</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>Standard Qualität 1:1 SW A4</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>Standard Qualität 1:1 SW A4</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>StapleStatus</key>
			<string>273</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>819.21258544921875</real>
					<real>572.598388671875</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-11.33856201171875</real>
					<real>-11.338600158691406</real>
					<real>830.55120849609375</real>
					<real>583.93695068359375</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>Standard Qualität 2:1 Duplex SW A4 </key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>Standard Qualität 2:1 Duplex SW A4 </string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>StapleStatus</key>
			<string>274</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>3</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>819.21258544921875</real>
					<real>572.598388671875</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-11.33856201171875</real>
					<real>-11.338600158691406</real>
					<real>830.55120849609375</real>
					<real>583.93695068359375</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>Standard Qualität 2:1 SW A4</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>Standard Qualität 2:1 SW A4</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>DuplexBindingEdge</key>
			<integer>3</integer>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>StapleStatus</key>
			<string>274</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>819.21258544921875</real>
					<real>572.598388671875</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-11.33856201171875</real>
					<real>-11.338600158691406</real>
					<real>830.55120849609375</real>
					<real>583.93695068359375</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
	<key>com.apple.print.customPresetNames</key>
	<array>
		<string>A4 SW 1:1 Super</string>
		<string>A4 SW 1:1 Normal</string>
		<string>A4 SW 1:1 Normal Duplex</string>
		<string>A4 SW 2:1 Entwurf Duplex</string>
		<string>A4 SW 2:1 Normal</string>
		<string>A4 SW 2:1 Normal Duplex</string>
	</array>
	<key>com.apple.print.lastPresetPref</key>
	<string>Standard Qualität 1:1 Duplex SW A4</string>
	<key>com.apple.print.lastPresetPrefType</key>
	<integer>4</integer>
	<key>com.apple.print.lastUsedSettingsPref</key>
	<dict>
		<key>com.apple.print.preset.id</key>
		<string>com.apple.print.lastUsedSettingsPref</string>
		<key>com.apple.print.preset.settings</key>
		<dict>
			<key>AP_D_InputSlot</key>
			<string></string>
			<key>AccessCodeValue</key>
			<string></string>
			<key>BookletBinding</key>
			<false/>
			<key>BoxNumberValue</key>
			<string></string>
			<key>BoxPasswordValue</key>
			<string></string>
			<key>ColorModel</key>
			<string>Gray</string>
			<key>DuplexBindingEdge</key>
			<integer>2</integer>
			<key>JobName</key>
			<string>1</string>
			<key>JobNameState</key>
			<string>0</string>
			<key>JobNameValue</key>
			<string>Dokument1</string>
			<key>KCCollate</key>
			<string>PrnDef</string>
			<key>KmCustomBoxPromptFlag</key>
			<string>Off</string>
			<key>KmEmailSettingsEnabled</key>
			<string>Off</string>
			<key>KmJobSettingsEnabled</key>
			<string>Off</string>
			<key>MediaType</key>
			<string>PrnDef</string>
			<key>PaperInfoIsSuggested</key>
			<true/>
			<key>Resolution</key>
			<string>600dpi</string>
			<key>StapleStatus</key>
			<string>273</string>
			<key>com.apple.print.PageToPaperMappingAllowScalingUp</key>
			<true/>
			<key>com.apple.print.PageToPaperMappingMediaName</key>
			<string>A4</string>
			<key>com.apple.print.PageToPaperMappingType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopies</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMCopyCollate</key>
			<true/>
			<key>com.apple.print.PrintSettings.PMDestinationType</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMDuplexing</key>
			<integer>2</integer>
			<key>com.apple.print.PrintSettings.PMFirstPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLastPage</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutColumns</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMLayoutNUp</key>
			<false/>
			<key>com.apple.print.PrintSettings.PMLayoutRows</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMOrientation</key>
			<integer>1</integer>
			<key>com.apple.print.PrintSettings.PMPageRange</key>
			<array>
				<integer>1</integer>
				<integer>2147483647</integer>
			</array>
			<key>com.apple.print.subTicket.paper_info_ticket</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>806</real>
					<real>559</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<real>-18</real>
					<real>-18</real>
					<real>824</real>
					<real>577</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PrintSettingsTicket</string>
			<key>job-sheets</key>
			<string>none</string>
		</dict>
	</dict>
</dict>
</plist>
" >> ~/Library/Preferences/com.apple.print.custompresets.forprinter.[3]-Ballroom-Printer.plist

exit 0