#!/bin/bash
# PBI-SSH-Setup v2.0

## Define variable(s)
operatingsystem=$(sw_vers -productVersion)
username="$(logname)"

## Define path for sshd_config
case $operatingsystem in
	10.10*) sshd_config="/etc/sshd_config";;
	10.11*) sshd_config="/etc/ssh/sshd_config";;
	10.12*) sshd_config="/private/etc/ssh/sshd_config";;
	*)
		/bin/echo "Error: This version of macOS is not supported."
		/usr/bin/logger "Error: PBI-SSH-Setup installation failed."
		exit 1
		;;
esac

## Create folder structure and define ACLs
if [ ! -d /Users/$username/.ssh ]; then
	/bin/mkdir /Users/$username/.ssh
fi
/bin/chmod 700 /Users/$username/.ssh

## Copy public keys to authorized_keys
/bin/cat > /Users/$username/.ssh/authorized_keys << EOF
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMjrRfL6f0W/w83PJ04rvQQ4rI63eRWF0PWXnoGoyLez paul.galow@point-blank-international.com
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDiYgB1D6absBbn/zAZ5V+LOAvto/2IdPDMuG5UolAHPuPzPZMzJQklajkHf8C3u+DqqDwllIgJpzBOPilan2a9zze0qH9a36/gvgBz2B5d6ZmG5yI8u55xrouUyA6yAjR8/qXhM8rqEmW1awSlzSJot+mBIrcUiVIQA/C+Bi0YomJjGMwZhusaoZ1JMq7QISQdzGBeB9S6Bp0f5e/WV5s/bDzS95nx/bmrbnP9ukSZUsGvaSE8ietv33gvCJY1ZsMa/DsdDFIl1mNgbIc6+1mWTdmzFb25ZGgkV3Si1BqOq/hhZxIBGoFvSdOyLjNun3V5/IXyyRJWRq6BJLcZaQDZmld5b7aOhCrWJVx4f25YW1YIJljjXPvjoNnRzgzvoKMClLflh3ictkYDO61Ax7J9NQqDgnVWxR6Soyst1yoj1z2E3o6trsEQ9AKKPTGqK1cW76Ai3aRf1LUzaM0NILyETbsbwQOZGN+V4GdNRuuKnQfD7rts86k2f8B1Wae3Mvje4sMwQLDTjB0ZVio+oQb4QYJ+794sowRJYfvHqBmzLdxOgdTzmOF5XnYJg3UUJoIm1HGc66F0aoiy0ay9d4vs4vxxOxo3q0cnJ5Px8CdXU/WBzD8c9Bq2nEzGSv+LatE66mJAizZev7zgfvuUFiWw4Vj42Aaq/aavRIBAyNz2GQ==
EOF

/bin/chmod 600 /Users/$username/.ssh/authorized_keys
/usr/sbin/chown -R $username:staff /Users/$username/.ssh

## Edit SSH configuration at /etc/sshd_config

# Create backup of current sshd_config
/bin/cp $sshd_config $sshd_config.bak

# Edit configuration parameters
/usr/bin/sed -E -i "" "s|^#?PasswordAuthentication yes|PasswordAuthentication no|" $sshd_config
/usr/bin/sed -E -i "" "s|^#?ChallengeResponseAuthentication yes|ChallengeResponseAuthentication no|" $sshd_config
/usr/bin/sed -E -i "" "s|^#?PermitRootLogin yes|PermitRootLogin no|" $sshd_config

## Restart SSH service
/bin/launchctl stop com.openssh.sshd

## Activate SSH remote login
/usr/sbin/systemsetup -f -setremotelogin on

/usr/bin/logger "PBI-SSH-Setup has been installed."
exit 0
